name: linux

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    matrix:
      python-version: ['3.6', '3.7', '3.8', '3.9']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: sudo apt-get install espeak-ng festival mbrola mbrola-fr1
      - name: Install phonemizer
        run: |
          pip install --upgrade pip
          python setup.py install
          pip install --upgrade pytest
      - name: Test phonemizer
        run: pytest
