# Test on Linux Ubuntu (festival-2.4 and espeak-ng-1.50) with various Python
# versions

name: Ubuntu - Python versions

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']

    steps:
      - name: Checkout phonemizer
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: sudo apt-get install espeak-ng festival mbrola mbrola-fr1

      - name: Install phonemizer
        run: |
          pip install --upgrade pip pytest pytest-cov
          python setup.py install

      - name: Version phonemizer
        run: phonemize --version

      - name: Test phonemizer
        run: pytest -v --cov=./phonemizer --cov-report=xml

      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.9' }}
        uses: codecov/codecov-action@v2
