# Test on Linux Ubuntu with various espeak versions

name: Ubuntu - Espeak versions

on: [push, pull_request]

jobs:
  espeak:
    runs-on: ubuntu-latest

  strategy:
    matrix:
      # espeak-version: ['1.48', '1.49.2', '1.50']
      espeak-version: ['1.49.2', '1.50']

    steps:
      - name: Checkout phonemizer
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2

      - name: Install system dependencies
        run: sudo apt-get install festival mbrola mbrola-fr1

      # - name: Install espeak-1.48
      #   if: ${{ matrix.espeak-version == '1.48' }}
      #   run:

      - name: Install espeak-1.49.2
        if: ${{ matrix.espeak-version == '1.49.2' }}
        run: |
          sudo apt-get install make autoconf automake libtool pkg-config gcc libsonic-dev libpcaudio-dev git
          git clone --depth 1 --branch 1.49.2 https://github.com/espeak-ng/espeak-ng.git
          cd espeak-ng
          ./autogen.sh
          ./configure
          make
          make install
          ldconfig
          espeak --version


      - name: Install espeak-1.50
        if: ${{ matrix.espeak-version == '1.50' }}
        run: |
          sudo apt-get install make autoconf automake libtool pkg-config gcc libsonic-dev libpcaudio-dev git
          git clone --depth 1 --branch 1.50 https://github.com/espeak-ng/espeak-ng.git
          cd espeak-ng
          ./autogen.sh
          ./configure
          make
          make install
          ldconfig
          espeak --version

      - name: Install phonemizer
        run: |
          pip install --upgrade pip pytest
          python setup.py install

      - name: Version phonemizer
        run: phonemize --version

      - name: Test phonemizer
        run: pytest -v
