# Test on Linux Ubuntu with various espeak versions

name: Ubuntu - Python versions

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        espeak-version: ['1.48', '1.49', '1.50']

    steps:
      - name: Checkout phonemizer
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2

      - name: Install system dependencies
        run: sudo apt-get install festival mbrola mbrola-fr1

      - name: Install espeak-1.48
        if: ${{ matrix.espeak-version == '1.48' }}
        run: sudo apt-get install espeak

      - name: Checkout espeak>=1.49
        uses: actions/checkout@v2
        with:
          repository: espeak-ng/espeak-ng
          path: espeak-ng
          ref: ${{ matrix.espeak-version }}

      - name: Install espeak>=1.49
        if: ${{ matrix.espeak-version >= '1.49' }}
        run: |
          sudo apt-get install libsonic-dev libpcaudio-dev
          cd espeak-ng
          ./autogen.sh
          ./configure
          make
          sudo make install

      - name: Install phonemizer
        run: |
          pip install --upgrade pip pytest
          python setup.py install

      - name: Version phonemizer
        run: phonemize --version

      - name: Test phonemizer
        run: pytest -v
