# Test on macos with festival-2.4 compiled from source and espeak-1.48 from
# homebrew. To save time and ressources, festival is cached across runs.

name: MacOS

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    # env:
    #   PHONEMIZER_FESTIVAL_EXECUTABLE: ${{ github.workspace }}/festival/build_festival/festival/bin/festival

    steps:
      - name: Checkout phonemizer
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5

      - name: Install espeak
        run: |
          brew update
          brew install espeak-ng

      - name: Check espeak
        run: espeak --version

      # do not work on apple silicon
      # - name: Cache festival
      #   uses: actions/cache@v4
      #   id: cache-festival
      #   with:
      #     path: ${{ github.workspace }}/festival
      #     key: ${{ runner.os }}-festival

      # - name: Checkout festival
      #   if: steps.cache-festival.outputs.cache-hit != 'true'
      #   uses: actions/checkout@v4
      #   with:
      #     repository: pettarin/setup-festival-mbrola
      #     path: festival

      # - name: Install festival
      #   if: steps.cache-festival.outputs.cache-hit != 'true'
      #   run: |
      #     cd festival
      #     bash setup_festival_mbrola.sh . festival

      # - name: Check festival
      #   run: |
      #     $PHONEMIZER_FESTIVAL_EXECUTABLE --version

      - name: Install phonemizer
        run: |
          pip install --upgrade pip setuptools
          pip install .[test,segments]

      - name: Version phonemizer
        run: phonemize --version

      - name: Test phonemizer
        run: pytest -v
