# Test on windows

name: Windows

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    env:
      PHONEMIZER_ESPEAK_PATH: "C:\\Program Files\\eSpeak NG\\espeak-ng.exe"
      PHONEMIZER_FESTIVAL_PATH: "C:\\festival\\src\\main\\festival.exe"

    steps:
      - name: checkout phonemizer
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2

      - name: install espeak
        run: |
          $source = 'https://github.com/espeak-ng/espeak-ng/releases/download/1.50/espeak-ng-20191129-b702b03-x64.msi'
          Invoke-WebRequest -Uri $source -OutFile espeak.msi
          Start-Process msiexec.exe -Wait -ArgumentList '/I espeak.msi /qn'

      - name: install festival
        run: |
          $source = "https://sourceforge.net/projects/e-guidedog/files/related-third-party-software/0.3/festival-2.5-win.7z"
          Invoke-WebRequest -Uri $source -OutFile festival-2.5.7z

          set-alias sz "$env:ProgramFiles\7-Zip\7z.exe"
          sz x festival-2.5.7z C:\

          # Expand-7Zip -ArchiveFileName $sourcefile -TargetPath 'C:\festival'

          # $sourcefile = "https://sourceforge.net/projects/e-guidedog/files/related-third-party-software/0.3/speech_tools-2.5-win.7z"
          # Expand-7Zip -ArchiveFileName $sourcefile -TargetPath 'C:\speech_tools'

      - name: install phonemizer
        run: |
          pip install --upgrade pip
          python setup.py install
          pip install --upgrade pytest

      - name: version phonemizer
        run: phonemize --version

      - name: test phonemizer
        run: pytest
