# Test on windows

name: Windows

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: checkout phonemizer
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2

      - name: install espeak
        run: |
          $source = 'https://github.com/espeak-ng/espeak-ng/releases/download/1.50/espeak-ng-20191129-b702b03-x64.msi'
          $destination = 'espeak-ng-20191129-b702b03-x64.msi'
          Invoke-WebRequest -Uri $source -OutFile $destination
          Start-Process msiexec.exe -Wait -ArgumentList '/I $destination /qn /L*v espeak-ng.log'
          Get-Content -Path espeak-ng.log
          Start-Process espeak-ng.exe -Wait -ArgumentList '--version'

      - name: install phonemizer
        run: |
          pip install --upgrade pip
          python setup.py install
          pip install --upgrade pytest

      - name: version phonemizer
        run: phonemize --version

      - name: test phonemizer
        run: pytest
