# Test on windows

name: Windows

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      # - name: checkout phonemizer
      #   uses: actions/checkout@v2

      # - name: setup python
      #   uses: actions/setup-python@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3

      - name: checkout espeak
        uses: actions/checkout@v2
        with:
          repository: espeak-ng/espeak-ng
          path: ${{ github.workspace }}/espeak-ng

      - name: checkout pcaudiolib
        uses: actions/checkout@v2
        with:
          repository: espeak-ng/pcaudiolib
          path: ${{ github.workspace }}/espeak-ng/src/pcaudiolib

      - name: install espeak
        run: |
          cd %GITHUB_WORKSPACE%\espeak-ng\src\windows
          msbuild
        shell: cmd

      - name: test espeak
        run: espeak-ng.exe --version


      # - name: install phonemizer
      #   run: |
      #     pip install --upgrade pip
      #     python setup.py install
      #     pip install --upgrade pytest

      # - name: version phonemizer
      #   run: phonemize --version

      # - name: test phonemizer
      #   run: pytest
