# Test on windows

name: Windows

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: checkout phonemizer
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2

      - name: checkout espeak
        uses: actions/checkout@v2
        with:
          repository: espeak-ng/espeak-ng
          path: espeak-ng

      - name: checkout pcaudiolib
        uses: actions/checkout@v2
        with:
          repository: espeak-ng/pcaudiolib
          path: espeak-ng/src

      - name: install espeak
        run: |
          choco install wixtoolset
          cd espeak-ng\src\windows
          msbuild espeak-ng.sln
        shell: cmd

      - name: install phonemizer
        run: |
          pip install --upgrade pip
          python setup.py install
          pip install --upgrade pytest

      - name: version phonemizer
        run: phonemize --version

      - name: test phonemizer
        run: pytest
