# Test on windows

name: Windows

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    env:
      PHONEMIZER_ESPEAK_PATH: "C:\\Program Files\\eSpeak NG\\espeak-ng.exe"

    steps:
      - name: checkout phonemizer
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2

      - name: install espeak
        run: |
          $source = 'https://github.com/espeak-ng/espeak-ng/releases/download/1.50/espeak-ng-20191129-b702b03-x64.msi'
          Invoke-WebRequest -Uri $source -OutFile espeak.msi
          Start-Process msiexec.exe -Wait -ArgumentList '/I espeak.msi /qn'

      - name: install phonemizer
        run: |
          pip install --upgrade pip
          python setup.py install
          pip install --upgrade pytest

      - name: version phonemizer
        run: phonemize --version

      - name: test phonemizer
        run: pytest
